### ISSUE TITLE
 "message" : "No authorization header supplied.",

### ISSUE THREAD

**Issue by thisismsreddy** [johanlundberg/neo4j-django-tutorial#3]
When i run the (python manage.py bootstrap)

neo4j.connection.OperationalError: Server returned unexpected response: 401{
  "errors" : [ {
    "message" : "No authorization header supplied.",
    "code" : "Neo.ClientError.Security.AuthorizationFailed"
  } ]
}

i know that I need to provide neo4j username and password how can provide information

**Comment by johanlundberg** [comment]
When I wrote the tutorial the authorization was not enabled by default (or maybe it didn't exist at all). Anyway, for this tutorial just disable authorization in the config file and restart the Neo4j server.

From http://neo4j.com/docs/stable/security-server.html,
```bash
# Disable authorization
dbms.security.auth_enabled=false
```

**Comment by prashant4nov** [comment]
when I run command python neo4jtut/manage.py syncdb, I am getting error: 
  File "/Users/Prashant/Documents/neo4j-django-tutorial/neo4jtut/apps/neo4japp/models.py", line 3, in <module>
    from neo4jtut import db
  File "/Users/Prashant/Documents/neo4j-django-tutorial/neo4jtut/neo4jtut/db.py", line 3, in <module>
    from neo4j import contextmanager
ImportError: No module named neo4j

**Comment by johanlundberg** [comment]
I have created a pull request for the upstream project to support connections with basic auth, https://github.com/jakewins/neo4jdb-python/pull/13.

If you want you can try it out using my branch, https://github.com/johanlundberg/neo4jdb-python/tree/basic_auth.

**Comment by thisismsreddy** [comment]
Thanks I am looking into it

**Comment by johanlundberg** [comment]
Fixed now with the release of neo4jdb 0.0.9.
