### ISSUE TITLE
neo4jdb-0.0.8 doesn't work with Python 3.5 + Neo4j 2.3.x

### ISSUE THREAD

**Issue by boltomli** [johanlundberg/neo4j-django-tutorial#5]
Upgrade to neo4jdb-0.0.9 can get the site up.

settings.NEO4J_PASSWORD)
TypeError: __init__() takes 2 positional arguments but 4 were given

**Comment by johanlundberg** [comment]
Thanks, I updated my code before 0.0.9 was out.
