### ISSUE TITLE
sqlite3.OperationalError: no such table: neo4japp_movie

### ISSUE THREAD

**Issue by brajaram** [johanlundberg/neo4j-django-tutorial#9]
Hi @johanlundberg,

When i execute the command, python neo4jtut/manage.py bootstrap, I am getting the below error.  Is there any file to load the sqlite3 database?  Appreciate your help.

Traceback (most recent call last):
  File "/Users/balajirajaram/anaconda/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/balajirajaram/anaconda/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: neo4japp_movie

**Comment by johanlundberg** [comment]
Did the command "python neo4jtut/manage.py migrate" run without errors?

Seems like the database table isn't created, which should be done by the above command.

**Comment by brajaram** [comment]
Yes, it ran without errors

python neo4jtut/manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK

**Comment by johanlundberg** [comment]
Hello again,

There where, as I could understand, two parts missing from my setup that has been supported since earlier in Django but not required as until recently.

First the app config in the neo4japp/apps.py, this also made me remove my previous apps module as it was being confusing.

Secondly the migrations directory with the initial database migrations is now required. I have added those.

Please have another try with the updated repository.

Thanks for the report!

**Comment by brajaram** [comment]
Thanks @johanlundberg 

It is working fine now.  However, I noticed the below exception

Exception ignored in: <bound method Connection.__del__ of <neo4j.bolt.connection.Connection object at 0x10de3f278>>
Traceback (most recent call last):

**Comment by johanlundberg** [comment]
Opening a new issue for the above report.
